### ISSUE TITLE
ChatService mock does not compile

### ISSUE THREAD

**Issue by vishalsodani** [alepez/devand#95]
Hi,

I have been able to build and run the application. But, I am not able to the serve static files. So, I tried running `yarn dev`. Will this build and copy the static assets? 

When I run `yarn dev` in devand-ui directory I am getting errors related to

```
error[E0063]: missing field `bio` in initializer of `devand_core::PublicUserProfile`
   --> src/app/services/chat_service/mock.rs:126:23
    |
126 |         members: vec![PublicUserProfile {
    |                       ^^^^^^^^^^^^^^^^^ missing `bio`

error[E0063]: missing field `bio` in initializer of `devand_core::User`
  --> src/app/services/code_now_service/mock.rs:62:5
   |
62 |     User {
   |     ^^^^ missing `bio`


```

and then

```


 ERROR in ./static/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./static/style.scss)
 Module not found: Error: Can't resolve './grids-responsive.css' in '/home/vishal/opensource/devand/devand-ui/static'
 @ ./static/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./static/style.scss) 4:40-114
 @ ./static/style.scss
 @ ./bootstrap-dev.js

  ERROR in ./static/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./static/style.scss)
  Module not found: Error: Can't resolve './pure.css' in '/home/vishal/opensource/devand/devand-ui/static'
 @ ./static/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./static/style.scss) 3:40-102
 @ ./static/style.scss
 @ ./bootstrap-dev.js

   ERROR in Rust compilation.
```

Thanks!

**Comment by guerinoni** [comment]
Try with `yarn run start:dev`

**Comment by alepez** [comment]
Thanks for the feedback. I think it's caused by one of the last commits. We haven't yet automated test on yew with mocked services, so we missed this bug. You can build the actual (not mocked) wasm files with `yarn run build`. It shouldn't give you errors, it's the command used during deployment.


Alessandro Pezzato
________________________________
Da: Vishal Sodani <notifications@github.com>
Inviato: venerdì 7 agosto 2020 12:03
A: alepez/devand
Cc: Subscribed
Oggetto: [alepez/devand] Compile error (#95)

Hi,

I have been able to build and run the application. But, I am not able to the serve static files. So, I tried running yarn dev. Will this build and copy the static assets?

When I run yarn dev in devand-ui directory I am getting errors related to

error[E0063]: missing field `bio` in initializer of `devand_core::PublicUserProfile`
   --> src/app/services/chat_service/mock.rs:126:23
    |
126 |         members: vec![PublicUserProfile {
    |                       ^^^^^^^^^^^^^^^^^ missing `bio`

error[E0063]: missing field `bio` in initializer of `devand_core::User`
  --> src/app/services/code_now_service/mock.rs:62:5
   |
62 |     User {
   |     ^^^^ missing `bio`


and then

`ERROR in ./static/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./static/style.scss)
Module not found: Error: Can't resolve './grids-responsive.css' in '/home/vishal/opensource/devand/devand-ui/static'
@ ./static/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./static/style.scss) 4:40-114
@ ./static/style.scss
@ ./bootstrap-dev.js

ERROR in ./static/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./static/style.scss)
Module not found: Error: Can't resolve './pure.css' in '/home/vishal/opensource/devand/devand-ui/static'
@ ./static/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./static/style.scss) 3:40-102
@ ./static/style.scss
@ ./bootstrap-dev.js

ERROR in Rust compilation.
`

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/alepez/devand/issues/95", "url": "https://github.com/alepez/devand/issues/95", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by alepez** [comment]
No @guerinoni, I think there's actually an error on the mock, we developed the "bio" feature, but we didn't add the new field in the mock (which is built only when mock feature is enabled)

**Comment by alepez** [comment]
So, until this is fixed, you must build the non-mocked version with **yarn run build**

**Comment by guerinoni** [comment]
@alepez 
Oh right, we forgot it eheheh

**Comment by vishalsodani** [comment]
What about the below error ? Why is it happening even if I run `yarn run build` ? 


```
ERROR in ./static/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./static/style.scss)
 Module not found: Error: Can't resolve './grids-responsive.css' in '/home/vishal/opensource/devand/devand-ui/static'
 @ ./static/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./static/style.scss) 4:40-114
 @ ./static/style.scss
 @ ./bootstrap-dev.js

  ERROR in ./static/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./static/style.scss)
  Module not found: Error: Can't resolve './pure.css' in '/home/vishal/opensource/devand/devand-ui/static'
 @ ./static/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./static/style.scss) 3:40-102
 @ ./static/style.scss
 @ ./bootstrap-dev.js

   ERROR in Rust compilation.

```

**Comment by vishalsodani** [comment]
The error on `yarn run build` is

```
ERROR in ./static/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./static/style.scss)
Module not found: Error: Can't resolve './grids-responsive.css' in '/home/vishal/opensource/devand/devand-ui/static'
 @ ./static/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./static/style.scss) 4:40-114
 @ ./static/style.scss
 @ ./bootstrap-prod.js

ERROR in ./static/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./static/style.scss)
Module not found: Error: Can't resolve './pure.css' in '/home/vishal/opensource/devand/devand-ui/static'
 @ ./static/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./static/style.scss) 3:40-102
 @ ./static/style.scss
 @ ./bootstrap-prod.js
error Command failed with exit code 2.
```

**Comment by alepez** [comment]
There are missing files. Please follow the README https://github.com/alepez/devand/blob/master/devand-ui/README.md

**Comment by vishalsodani** [comment]
> There are missing files. Please follow the README https://github.com/alepez/devand/blob/master/devand-ui/README.md

Thanks! Works now.
